#  This file goes into etc/security
#        - chroot - change root to directory (Debian-specific)
#
#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#root            hard    core            100000
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#ftp             -       chroot          /ftp
#@student        -       maxlogins       4
* soft    memlock    unlimited
* hard    memlock    unlimited
@audio  soft    memlock    unlimited
@audio  hard    memlock    unlimited
@audio - memlock 256000   
@audio - rtprio 75

